In [45]:
import pandas as pd
import requests

In [46]:
api_url = "https://raw.githubusercontent.com/owid/covid-19-data/refs/heads/master/public/data/latest/owid-covid-latest.json"
response = requests.get(api_url)
raw_data = response.json()

new_df = pd.DataFrame(raw_data)
new_df = new_df.transpose()

assert new_df.shape == (247, 66), "dataframe is incorrect shape"

In [47]:
df = pd.DataFrame(raw_data)

value = raw_data["MMR"]
value 
df = pd.json_normalize(value)
df

  continent location  ... excess_mortality  excess_mortality_cumulative_per_million
0      Asia  Myanmar  ...             None                                     None

[1 rows x 66 columns]

In [49]:
result_df = pd.DataFrame()

for key in raw_data.keys():
    row = raw_data[key]
    row_df = pd.json_normalize(row)
    result_df = pd.concat([result_df, row_df], ignore_index=True)

assert new_df.shape == (247, 66), "dataframe is incorrect shape"

result_df

/tmp/ipykernel_6565/3069688062.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  result_df = pd.concat([result_df, row_df], ignore_index=True)

    continent  ... excess_mortality_cumulative_per_million
0        Asia  ...                                    None
1        None  ...                                    None
2      Europe  ...                                    None
3      Africa  ...                                    None
4     Oceania  ...                                    None
..        ...  ...                                     ...
242   Oceania  ...                                    None
243      None  ...                                    None
244      Asia  ...                                    None
245    Africa  ...                                    None
246    Africa  ...                                    None

[247 rows x 66 columns]